#!/bin/sh
alias gs="git status"
alias editzsh="vim ~/.zshrc"
alias cat="bat"
alias ls="eza --color=always --long --git --no-filesize --icons=always --no-time --no-user --no-permissions --tree --level=1"
alias tree="ls --tree --level=9"
alias vim="nvim"
alias nivm="nvim"
alias nim="nvim"
alias nimv="nvim"
alias cp="/usr/local/bin/cpg -g"
alias mv="/usr/local/bin/mvg -g"
alias lg='lazygit'
alias nuke="git reset --hard HEAD && git clean -fd"
alias stremio="flatpak run com.stremio.Stremio"
alias restart-app="./stop.sh && sleep 3 && ./start.sh"
alias npm="pnpm"
alias npx="pnpm dlx"
