alias gs="git status"
alias wtf="tldr"
alias wth="man"
alias editzsh="vim ~/.zshrc"
alias reload=". ~/.zshrc"
alias vimhelp="cat ~/vimmovs.txt"
alias cat="bat"
alias ls="eza --color=always --long --git --no-filesize --icons=always --no-time --no-user --no-permissions --tree --level=3"
